from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.signout, name='signout'),
    path('login/', views.signin, name='signin'),
    path('home/', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('no-disponible/', views.error_handle, name='error_handle'),
    path('upload1/', views.upload_file, name='upload_file'),
    path('mapaZoom/', views.mapaZoom, name='mapaZoom'),
    path('mapa/', views.mapa, name='mapa'),
    path('charts/', views.charts, name='charts'),
    path('modelo-MERCADOS/', views.upload, name='upload'),
    path('data/', views.data, name='data'),
    path('descargas/', views.descargar_excel, name='descargar_excel'),
    path('about/', views.about, name='about'),
    path('newsletter/', views.dashboard_newsletter, name='dashboard_newsletter'),
    path('precios-de-mercado/', views.dashboard_precios_de_mercado, name='preciosDeMercado'),
    path('PPA/', views.dashboard_PPA, name='PPA'),
    path('calculo-volatidad/', views.dashboard_CVolatilidad, name='volatidad'),
    path('areas-zonas/', views.dashboard_Areas_y_Zonas, name='areasZonas'),
    path('acceso-ofertas-de-compra/', views.verificar_contrasena, name='verificarContraseña'),
    path('acceso-estados-de-cuenta/', views.verificar_contrasena_temporal, name='verificarContraseñaTemporal'),
    path('A/', views.dashboard_A, name='A'),
    path('consulta-de-facturas/', views.dashboard_facturas, name='facturas'),
    path('facturacion-y-edc/', views.facturacion_y_edc, name='facturacionEdc'),
    path('Facturacion/', views.Facturas, name='Facturas'),
    path('rea-test/', views.rea_test, name='reaTest'),
    path('calculo-REA/', views.calculo_rea, name='calculoREA'),
    path('estados-de-cuenta/', views.index, name='estadosDeCuenta'),
    path('conciliacion/', views.index, name='conciliacion'),
    path('conciliacion<fecha>/', views.conciliacion1, name='conciliacionFecha'),
    path('consultas-MERCADOS/', views.Consultas_mercados, name='consultasMercados'),
    path('WS-ODC/', views.dashboard_WS_ODC, name='WSODC'),
    path('commodities/', views.dashboard_commodities, name='commodities'),
    path('web-service/', views.dashboard_webservice, name='webService'),
    path('demanda/', views.dashboard_demanda, name='demanda'),
    path('ofertas-de-venta/', views.dashboard_ofertas_de_venta, name='ofertasDeVenta'),
    path('Mediem/', views.dashboard_Medimem, name='Mediem'),
    path('ODC-DB/', views.consulta_odc_db, name='ODCDB'),
    path('generacion-de-energia/', views.dashboard_generacion_de_energia, name='generacionDeEnergia'),
    path('energia-asignada/', views.dashboard_energia_asignada, name='energiaAsignada'),
    path('ofertas-de-compra/', views.dashboard_ofertas_de_compra, name='ofertasDeCompra'),
    path('servicios-conexos/', views.dashboard_servicios_conexos, name='serviciosConexos'),
    path('Mediem-consulta/', views.dashboard_Medimem_querys, name='MediemConsulta'),
    path('Mediem-Beetmann/', views.dashboard_medimem_btmnn, name='MediemBeetmann'),
    path('consumo-cliente-Beetmann/', views.consumo_cliente_beetmann, name='consumoClienteBeetmann'),
    path('clientes-firmados/', views.dashboard_clientes_firmados, name='clientesFirmados'),
    path('tarifa-CFE/', views.dashboard_Tarifa_CFE, name='tarifaCFE'),
    path('ODB-DB-Consulta/', views.dashboard_ODB_DB_querys, name='ODBDBConsulta'),
    path('repositorio/', views.repositorio, name='repositorio'),
    path('repositorio/<path:archivo>', views.repositorio, name='respositorioArchivo'),
    path('re/', views.re, name='re'),
    path('z/', views.chart, name='z'),
    path('graficaZoom/', views.graficaZoom, name='graficaZoom'),
    path('rentabilidad-Beetmann/', views.dashboard_Rentabilidad, name='rentabilidadBeetmann'),
    path('descarga-recibo-cfe/', views.upload_file_cfe, name='descargaReciboCFE'),
    
    
]